# Generated by Django 3.2.7 on 2021-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurante', models.CharField(help_text='Ingrese el Nombre del Restaurante', max_length=300, verbose_name='Nombre del Restaurante')),
            ],
        ),
    ]
