# Generated by Django 3.2.7 on 2021-10-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20211002_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='descripcion_slider',
            field=models.CharField(blank=True, help_text='descripcion del slider', max_length=250, null=True, verbose_name='aqui va la informacion del slider'),
        ),
        migrations.AddField(
            model_name='restaurantes',
            name='slider_Del_restaurante',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
