# Generated by Django 3.2.7 on 2021-10-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20211002_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantes',
            options={'verbose_name': 'Restaurantes'},
        ),
    ]
