# Generated by Django 3.2.7 on 2021-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='agrege el numbre del conductor', max_length=250, null=True, verbose_name='Nombre del Conductor')),
                ('telefon', models.IntegerField(blank=True, help_text='agrege el numero telefonico', null=True, verbose_name='ingrese el numero de contacto')),
                ('direcction', models.TextField(blank=True, help_text='agrege la direcion', null=True, verbose_name='agrege la direcion del conductor')),
                ('esta_disponible', models.IntegerField(choices=[(1, 'SI'), (2, 'NO')])),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='esta_disponible',
            field=models.IntegerField(choices=[(1, 'SI'), (2, 'NO')]),
        ),
    ]
