# Generated by Django 3.2.7 on 2021-10-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20211005_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_order_realizada', models.DateTimeField(auto_now_add=True)),
                ('nombres', models.CharField(blank=True, help_text='here goes the name of the customer', max_length=250, null=True, verbose_name='nombre del cliente')),
                ('apellidos', models.CharField(blank=True, help_text=' here goes the lastnames of the customer', max_length=250, null=True, verbose_name='appellidos del cliente')),
                ('numero_telefono', models.IntegerField(blank=True, help_text='aqui va el el telefono del cliente', max_length=10, null=True, verbose_name='ingrese nuero de client')),
                ('correo_elect', models.EmailField(help_text='este es el email', max_length=254, verbose_name='Correo Electronico')),
                ('departament', models.IntegerField(choices=[(1, 'San Salvador')])),
                ('direccion_uno', models.CharField(blank=True, help_text='aqui va la direccion 1', max_length=250, null=True, verbose_name='dereccion 1')),
                ('direccion_dos', models.CharField(blank=True, help_text='aqui va la direccion 2', max_length=250, null=True, verbose_name='direccion 2')),
                ('ciudad', models.IntegerField(choices=[(1, 'San Salvador'), (2, 'otra ciudad')])),
                ('opciones_entrega', models.IntegerField(choices=[(1, 'Delivery'), (2, 'Recoger en Tienda')], verbose_name='opcion selecionada por el cliente')),
                ('notas', models.TextField()),
                ('estado_de_la_orden', models.IntegerField(choices=[(1, 'realizada'), (2, 'en cocina'), (3, 'en delivery'), (4, 'entregada'), (5, 'anulada')])),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.conductor')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantes')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
    ]
